### ISSUE TITLE
A strange upload error.

### ISSUE THREAD

**Issue by nehcoab** [wagiminator/AVR-Programmer#10]
Hi, Stefan. I encountered a very strange error.

I programmer an ATTINY13A-SSU with MicroCore use your AVR Programmer Adapter Maxi. When I set the clock to '1.2 Mhz internal osc', everything works fine. However, when I switch to '8 MHz external clock', it works the first time, but then it never works again, I mean that an upload error occurred, no matter what the clock is set to. This means that this MCU is no longer able to be programmed. I tried several MCUs, and the same issue occurred with all of them. On one occasion, even when I set the clock to '1MHz external clock', it worked the first time too, but then it failed every time after that. I noticed that the [8MHz resonator I purchased](https://www.lcsc.com/product-detail/Ceramic-Resonators_Murata-Electronics-CSTLS8M00G53-B0_C83707.html) is blue, while the one in your picture is brown. I'm not sure if this has anything to do with it.

I've included the error message below for your reference:
```
Sketch uses 328 bytes (32%) of program storage space. Maximum is 1024 bytes.
Global variables use 1 bytes (1%) of dynamic memory, leaving 63 bytes for local variables. Maximum is 64 bytes.
avrdude error: cannot set sck period; please check for usbasp firmware update
avrdude error: program enable: target does not answer (0x01)
avrdude error: initialization failed, rc=-1
        - double check the connections and try again
        - use -B to set lower ISP clock frequency, e.g. -B 125kHz
        - use -F to override this check

Failed programming: uploading error: exit status 1
```

Any help you can provide would be greatly appreciated.

Thank you!

**Comment by wagiminator** [comment]
Hi,
the ATtiny13A does not support an external oscillator, it needs an external clock signal on pin PB3 (CLKI). In order to unbrick your chips you have either to provide the clock signal (let's say a 1MHz square wave) on PB3 while reprogramming, or you need a high-voltage serial programmer, e.g. https://github.com/wagiminator/ATtiny84-TinyHVSP.

**Comment by nehcoab** [comment]
Thank you for the solution provided, I will attempt to unbrick my chips accordingly, and I will return to provide feedback on the results.

**Comment by nehcoab** [comment]
> Hi, the ATtiny13A does not support an external oscillator, it needs an external clock signal on pin PB3 (CLKI). In order to unbrick your chips you have either to provide the clock signal (let's say a 1MHz square wave) on PB3 while reprogramming, or you need a high-voltage serial programmer, e.g. https://github.com/wagiminator/ATtiny84-TinyHVSP.

Great, I made the TinyHVSP, my chips are worked.

![iss10](https://github.com/wagiminator/AVR-Programmer/assets/33834826/8e7acdc9-3c1e-47bb-b796-a19d79b43aa1)

**Comment by wagiminator** [comment]
;-)
