### ISSUE TITLE
Upload sketch with SerialUPDI HV Programmer doesn't work

### ISSUE THREAD

**Issue by avandalen** [wagiminator/AVR-Programmer#6]
Hi Stefan
Uploading sketches gives an error message with the megaTinyCore version 2.6.10.
Can you test this out? I also reported the problem here:
https://github.com/SpenceKonde/megaTinyCore/issues/1076

**Comment by wagiminator** [comment]
Hi, 
I just tested it again on Linux with Arduino IDE v1.8.13 and megaTinyCore 2.6.10 (Programmer: Serial UPDI - 230400 baud). It works for me. When I look at the screenshot of your scope, I don't really see a problem. Strange. Try "Burn bootloader".
