### ISSUE TITLE
What does picoAVR actually compatible with? USBASP or USBtinyISP?

### ISSUE THREAD

**Issue by xinaovo** [wagiminator/AVR-Programmer#8]
Hi,
The Readme.md in the github repository says picoAVR is compatible with USBASP. However, the description on OSHWLab says it's compatible with USBtinyISP. It seems they are contradictory, or picoAVR is compatible with both USBASP and USBtinyISP?

![屏幕截图 2024-05-17 182718](https://github.com/wagiminator/AVR-Programmer/assets/107630526/f46b9340-1ea2-4774-bb7c-ff6d74ea4031)

![屏幕截图 2024-05-17 182801](https://github.com/wagiminator/AVR-Programmer/assets/107630526/ff426337-4cc9-4a24-b4f2-12f0458a727b)

**Comment by wagiminator** [comment]
Hi, the description on OSHWLab is outdated. When I find the time, I'll update it. The current firmware is compatible with USBasp. I made this change some time ago because of the TPI feature.
